config/routes.rb
Rails.application.routes.draw do
  
  get '/about' => 'home#about'
  
  get '/allquotes' => 'allquotes#manyquotes'
  
  get '/signup' => 'registrations#new'

  post '/signup' => 'registrations#create'
  
  delete '/logout' => 'sessions#destroy'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/addquote' => 'addquote#new'
  
  post '/addquote' => 'addquote#create'

  get '/profile' => 'home#profile'
  
  root 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :desc, presence: true, length: {maximum: 200}
  validates :name, presence: true, length: {maximum: 200}
  validates :username, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :email, presence: true
end

app/controllers/addquote_controller.rb
class AddquoteController < ApplicationController
  def new
    if session[:user_id]
      @quote = Quote.new
      @user = User.find_by(id: session[:user_id])
    else
      redirect_to login_path
    end
  end
  
  def create
    @user = User.find_by(id: session[:user_id])
    @quote = Quote.new(quote_params)
    @quote.username = @user.email
    @quote.save
    redirect_to allquotes_path
  end
  
  private
  def quote_params
    params.require(:quote).permit(:name, :desc)
  end
end

app/controllers/allquotes_controller.rb
class AllquotesController < ApplicationController
  def manyquotes
  	if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
    all_quotes = Quote.all
    @quotes = all_quotes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
    quote_count = Quote.all.count
    num = (1..quote_count).to_a.shuffle.first
    @quote = Quote.find_by(id: num)
    @result = @quote.desc
    input = @quote.username
    d = ""
    input.split('').each { |c| 
      if c == '@'
        break
      else
        d += c
      end
    }
    @author = d
  end
  
  def about
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
    
  end

  def profile
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
    @quotes = Quote.where(["username = ?", @user.email])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def new
		render :new
	end

	def create
		@user = User.create(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Account created successfully!"
		else
			render :new
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		render :new
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "Successfully Logged out!"
	end

	def create
		user = User.find_by(email: params[:email])
		if user.present? && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: "Logged in successfully!"
		else
			flash[:alert] = "Invalid email or password"
			render :new
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/addquote/new.html.erb
<h1>Add Quote</h1>

<%= form_for :quote do |form| %>
  <div class="mb-3">
    <p1 class="m-3">Tag</p1>
    <%= form.text_field :name, class: "form-control", placeholder: "Tag" %>
  </div>
  <div class="mb-3">
    <p1 class="m-3">Add Quote</p1>
    <%= form.text_field :desc, class: "form-control", placeholder: "Insert Quote" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Add Quote", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/allquotes/manyquotes.html.erb
<% provide(:title, "Quotes") %>

<h1 class="my-4">All Quotes</h1>
<div class="container bg-white rounded border border-dark mb-4 p-3">
  <% @quotes.each do | quote | %>
  	<div class="card m-5">
        <div class="card-body">
        	<blockquote class="blockquote text-center mb-0">
        		<p style="color: black">Tag: <%= quote.name %></p>
                <p style="color: black">"<%= quote.desc %>"</p>
            </blockquote>
        </div>
    </div>
  <% end %> 
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Random Quote</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Quotes', allquotes_path, class: "nav-link" %>
      </li>
      </ul>
      <ul class="navbar-nav ml-auto">
      <% if @user %>
          <li class="nav-item">
            <%= link_to 'Add Quotes', addquote_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <span class="nav-link">Hi <%= @user.email %></span>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', logout_path, class: "nav-link", method: :delete %>
          </li>
          <li class="nav-item">
            <%= link_to 'Profile', profile_path, class: "nav-link"%>
          </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="row">
  <div class="col m-5">
      <h1>About this website</h1>
  </div>
</div>
<div class="row">
  <div class="col mb-5">
    <div class="card">
        <div class="card-body">
          <blockquote class="blockquote text-center mb-0">
            <p id="words">
              This website is designed to receive random quotes people submit to it. To view all the quotes click the Quotes Tab. Sign up, add a quote, enjoy!
              <br>
              You will also be able to keep a track of your own quotes.
              <br>
              The image on the front page is from a Tumblr user called "tiffyquake".
            </p>
          </blockquote>
        </div>
    </div>
    
  </div>
<div class="row">
  <div class="col">
    <div class="card">
        <div class="card-body">
          <blockquote class="blockquote text-center mb-0">
            <p id="words">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
          </blockquote>
        </div>
    </div>
    
  </div>
  <div class="col">
    <div class="card">
        <div class="card-body">
          <blockquote class="blockquote text-center mb-0">
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
          </blockquote>
        </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col m-5">
    <div class="card">
        <div class="card-body">
          <blockquote class="blockquote text-center mb-0">
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
          </blockquote>
        </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
  <div class="row">
    <div class="col p-5 m-5">
      <div class="mb-3 pb-4" id="skies" role="img" aria-label="Purple/orange skies">
        <h1 class="mt-5 p-5">Welcome to the Random Quote Generator</h1>
        <div class="d-flex justify-content-center mb-3">
          <%= link_to 'Random Quote', root_path, class: "btn btn-primary"%>
        </div>
        <div class="card m-5">
          <div class="card-header text-center" style="color: black">
            Your quote is:
          </div>
          <div class="card-body">
            <blockquote class="blockquote text-center mb-0">
              <p style="color: black">"<%= @result %>"</p>
              <p style="color: black"> --- <%= @author %></p>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/home/profile.html.erb
<% provide(:tag, "Quotes") %>
<% if !@quotes.present? %>
  <div class="container bg-white rounded border border-dark mt-4 p-3">
    <div class="card m-5">
        <div class="card-body">
          <blockquote class="blockquote text-center mb-0">
            <p style="color: black">You have not added any quotes yet! Feel free to add one!</p>
            </blockquote>
        </div>
    </div>
  </div>
<% else %>
  <h1 class="my-4">My Quotes</h1>
  <div class="container bg-white rounded border border-dark mb-4 p-3">
    <% @quotes.each do | quote | %>
  	 <div class="card m-5">
        <div class="card-body">
        	<blockquote class="blockquote text-center mb-0">
        		<p style="color: black">Tag: <%= quote.name %></p>
            <p style="color: black">"<%= quote.desc %>"</p>
          </blockquote>
        </div>
      </div>
    <% end %> 
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
      <%= yield %>
    </div>
    
    </body>
</html>